algoritmo "semnome"
var
numA, numB, numC:real
calculo:real
inicio
escreval("Digite um número que sera o número A")
leia(numA)
escreval("Digite um número que sera o número B")
leia(numB)
escreval("Digite um número que sera o número C")
leia(numC)
limpatela
calculo <- numA+numB
se(calculo<numC)Entao
escreval("O calculo dos numeros A e B são menores que o numero C.")
senao
escreval("O calculo dos numeros A e B não são menores que o numero C.")
Fimse

fimalgoritmo
